var excuses = [
  'I was Not feeling well.',
  'I was absent that day.',
  'I HAVE TO GO TO COURT.',
  'I HAVE TO STUDY FOR A MIDTERM.',
  'I BROKE MY TAILBONE.',
  'I JUST GOT A ROOT CANAL.',
  'There was too much traffic',
  'A family member was sick.',
  'I was stopped by the police',
  'My phone was dead.',
  'had a family emergency.',
  'had a house emergency,',
  'i thought it was holiday today',
  'MY APARTMENT IS FLOODING.',
  'I NEED TO TAKE MY ROOMMATE TO THE HOSPITAL.',
  'My brother is very sick',
  'I had TO HELP MY SISTER MOVE.',
  'Had a nut ALLERGY',
  'MY CAR GOT A FLAT TIRE.',
  'I had to bring my work today?',
  'believe me',
  'had a doctor’s appointment',
  'A family event',
  'no',
  'yes',
  '"i won\'t help you this time" \n-book of excuses ✌',
  'I had a bad night last night.',
  'I ate something bad at lunch, so I can’t come back to work because I have an upset stomach.',
  'I have a family emergency.',
  "I have to take my cat (dog, bird, rabbit, horse) to the vet.",
  'I have a sick relative who\'s having surgery today and my family needs me at the hospital.',
  'I have really bad cramps. (This one only works for women)',
  'My foot hurts.',
  'I have low blood sugar',
  'It’s my friend’s birthday.',
  'I DON’T HAVE ENOUGH TIME.',
  'I need to go to the post office',
  'My bike got a puncture',
  'My car got a puncture',
  'I have to go pay electricity bill',
  'I have to go pay mobile bill',
  'My friend is going through a rough time right now',
  'I have work early tomorrow',
  'I’m broke.',
  'My wallet was stolen',
  'My phone was stolen',
  'I totally forgot, my mom is in town tonight',
  'I don\'t want to be in the same room as XYZ',
  'Sorry I fell asleep',
  'My phone got a cracked screen, Gotta get it fixed',
  'I\'m feeling dehydrated',
  'I have a severe headache',
  'My mom isn\'t allowing me',
  'It\'s my cousin\'s wedding',
  'It\'s my friend\'s Bachelor/Bachelorette party',
  'I have music lessons today',
  'I have cooking class today',
  'I fell down yesterday and can\'t walk ',
  'My shower isn\'t working',
  'Urgent meeting with boss',
  'Gotta go shopping with sister',
  'I have an order coming in that I have to present for',
  'There is no one to watch my pet and it cannot be home by itself',
  'I have to go shopping for the upcoming event',
  'My friend had an accident',
  'My collegue needs my assistance',
  'I burned by arm on the stove',
  'There was a gas leak in my building',
  'There was a robbery in my building',
  'The water pipe in my house burst',
  'Relatives came home',
  'I need to clean my house',
  'I have some personal emergency',
  'I need to get my office work done today',
  'My neighbour needs help moving out',
  'My new neighbour needs help moving in',
  'I have the virus',
  'I\'m having chest pains',
  'I\'ve got a serious migrane',
  'My colleague just called in sick, I have to cover his shift',
  'I have to pick up my younger brother',
  'I’ve got some stuff going on and I think that would make it difficult to be around me at the moment',
  'I have an upset stomach',
  'Just had a break up',
  'No cab available',
  'I have to wait for the internet technician to come over and he still hasn’t shown.',
  'I have back problems since morning',
  'I have knee problems since morning',
  'My ears are paining',
  'My neck hurts, I can\'t move it a bit',
  'Uber and Ola are too costly right now',
  'It might anytime and my area gets flooded quickly',
  'My society is under lockdown because of positive cases',
  'My society is having a meeting and I need to be there',
  'My uncle needs help with his computer stuff',
  'My cousin has exams tomorrow and they need my help',
  'I have food poisoning',
  'I have had a short curcuit in my house',
  'AC installation guy is coming today',
  'Geyser installation guy is coming today',
  'Mom\'s birthday today'
];
